export default {
	goodId: '', // 芯片编号
	name: '', // 姓名
	price: '', // 价格
	sex: '',	// 性别
	age: '',    // 年纪
	birth_date: '', // 出身日期
	birth_place: '', // 出身地
	breed: '', // 犬种
	varieties: '', // 品种
	sell_state: '', // 出售状态
	sell_place: '', // 出售地
	is_hot: '', // 是否热门
	good_desc: '', // 产品描述
	is_competition: '', // 是否参赛
	is_winning: '', // 是否获奖
	winning_rank: '', // 获奖名次
	host_unit: '', // 主办单位
	father: '000000000000000000000000', // 父亲
	mother: '000000000000000000000000', // 母亲
	first_vaccine_time: '', // 第一次注射时间
	first_vaccine_name: '', // 第一次疫苗名称
	first_vaccine_type: '', // 第一次疫苗
	second_vaccine_time: '', // 第二次注射时间
	second_vaccine_name: '', // 第二次疫苗名称
	second_vaccine_type: '', // 第二次疫苗
	third_vaccine_time: '', // 第三次注射时间
	third_vaccine_name: '', // 第三次疫苗名称
	third_vaccine_type: '', // 第三次疫苗
	body_surface: '', // 体表
	back_hair: '', // 背毛
	eye_color: '', // 眼睛颜色
	hair_color: '', // 毛色
	shape: '', // 体型
	courage: '', // 胆量
	attack: '', // 攻击性
	xianqu: '', // 衔取
	sport_temp: '', // 运动气质
	head_imgs: [], // 头部图片
	figure_imgs: [], // 身段图片
	sport_imgs: [], // 运动图片
	videoUrl: '', // 视频地址
}
